version: 2
updates:

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  # rocm-systems submodule
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
    - dependency-name: "rocm-systems"
    schedule:
      interval: "daily"
